config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  devise_for :users, controllers: { sessions: "users/sessions" }

  authenticate :user, lambda { |u| u.decorate.administrator? } do
    mount MissionControl::Jobs::Engine, at: "/admin/jobs"
  end

  resources :posts, param: :slug do
    resources :feedbacks, only: %i[index create]
  end

  get "/users/posts", to: "posts#by_author"
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  enum :status, { public: 0, private: 1, archived: 2 }, validate: true, default: :public, suffix: true

  belongs_to :user, inverse_of: :posts

  has_many :feedbacks, inverse_of: :post, dependent: :destroy

  has_rich_text :content

  # broadcasts_refreshes

  validates :title,
            presence: true,
            uniqueness: {
              case_sensitive: false
            },
            format: %r{\A[a-zA-Z0-9\s\-\[\]/*&;,._:()!?ñÑ]*\z}
  validates :content, presence: true

  scope :public_status,
        ->(search = "") do
          search = search&.strip

          if search.present?
            joins(:rich_text_content)
              .where(status: :public)
              .where("to_tsvector('english', title) @@ websearch_to_tsquery(?)", search)
              .or(merge(ActionText::RichText.with_body_containing(search)))
          else
            where(status: :public)
          end
        end

  scope :by_author,
        ->(author_id, search = "") do
          search = search&.strip

          if search.present?
            joins(:rich_text_content)
              .where(user_id: author_id)
              .where("to_tsvector('english', title) @@ websearch_to_tsquery(?)", search)
              .or(merge(ActionText::RichText.with_body_containing(search)))
          else
            where(user_id: author_id)
          end
        end

  # Whether to generate a new slug.
  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :check_user, only: %i[edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]

  # Defines a helper method to access decorated instance variables.
  decorates_assigned :posts, :post, :feedbacks

  # GET /posts
  def index
    posts = Post.includes(%i[user rich_text_content]).public_status(params[:search]).order(updated_at: :desc)
    @pagy, @posts = pagy_countless(posts, limit: 10)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /posts/1
  def show
    redirect_to posts_url and return if !@post.public_status? && @post.user_id != current_user&.id

    @post_feedbacks_count = @post.feedbacks.count
    feedbacks = @post.feedbacks.includes([:user]).order(created_at: :desc)
    @pagy, @feedbacks = pagy_countless(feedbacks, limit: 10)
    @feedback = @post.feedbacks.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create # rubocop:disable Metrics/AbcSize
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: t("record.create", record: Post.name, name: @post.title) }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordNotUnique => e
    @post.errors.add(:base, e)
    render :new, status: :unprocessable_entity
  end

  # PATCH/PUT /posts/1
  def update # rubocop:disable Metrics/AbcSize
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: t("record.update", record: Post.name, name: @post.title) }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordNotUnique => e
    @post.errors.add(:base, e)
    render :edit, status: :unprocessable_entity
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: t("record.delete", record: Post.name, name: @post.title) }
      format.json { head :no_content }
    end
  end

  def by_author
    posts =
      Post.includes([:rich_text_content]).by_author(current_user.id, params[:search]).order(updated_at: :desc)
    @pagy, @posts = pagy_countless(posts, limit: 10)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  private

  def check_user
    current_user.posts.find_by_friendly_id(params[:slug]) # rubocop:disable Rails/DynamicFindBy
  rescue ActiveRecord::RecordNotFound
    logger.error "User Post not found #{params[:slug]}"
    redirect_to posts_url, warning: t(:not_authorized)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find_by_friendly_id(params[:slug]) # rubocop:disable Rails/DynamicFindBy
  rescue ActiveRecord::RecordNotFound
    logger.error "Post not found #{params[:slug]}"
    redirect_back(fallback_location: posts_url)
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :status).each_value { |value| value.try(:strip!) }
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def post_author?(author_id)
    author_id == current_user&.id
  end
end

app/views/posts/_filter.html.slim
- path ||= posts_path
div class="d-flex mb-3"
  = form_with(url: path, method: :get,
    data: { turbo_frame: :posts, controller: "posts", action: "input->posts#submitFilter" }) do |f|
    = f.search_field :search, value: params[:search], class: "form-control",
      placeholder: t(".search_posts"), aria: { label: t(".search") }

app/views/posts/_form.html.slim
- submit_label = post.new_record? ? t(".create") : t(".update")

= form_with(model: post) do |form|
  == render "partials/errors", errors: post&.errors&.full_messages || []
  .row.mb-3
    .col
      = form.label :title, t(".title"), class: "form-label"
      = form.text_field :title, class: "form-control"
      / == render "partials/errors", errors: post.errors.full_messages_for(:title)
  .row.mb-3
    .col
      = form.label :status, t(".status"), class: "form-label"
      = form.select :status, enum_for_select(Post, :status),
        {}, class: "form-select"
      / == render "partials/errors", errors: post.errors.full_messages_for(:status)
  .row.mb-3
    .col
      = form.label :content, t(".content"), class: "form-label"
      = form.rich_text_area :content, class: "form-control"
      / == render "partials/errors", errors: post.errors.full_messages_for(:content)
  = form.submit submit_label, class: "btn btn-primary btn-sm"

app/views/posts/_post.html.slim
.col
  / = turbo_stream_from post
  .card.h-100
    = image_tag "https://placehold.co/20x10", loading: "lazy", alt: "...", class: "card-img-top"
    .card-body
      h5.card-title
        = link_to post.title, post, class: "stretched-link", data: { turbo_frame: "_top" }
      .card-text.line-clamp
        = post.content
    .card-footer
      - if current_page?(users_posts_path)
        small.text-muted
          - if post.created_at == post.updated_at
            | Posted&nbsp;
            = post.created_time_ago
          - else
            | Edited&nbsp;
            = post.updated_time_ago
      - else
        .d-flex.flex-row.align-items-center
          .fw-semibold.me-2 = post.author
          span.dot
          small.text-muted.ms-2
            - if post.created_at == post.updated_at
              | Posted&nbsp;
              = post.created_time_ago
            - else
              | Edited&nbsp;
              = post.updated_time_ago

app/views/posts/_turbo_stream_replace_pagination.html.slim
= turbo_stream.replace :pagination do
  - if @pagy.next.present?
    - src ||= posts_path(format: :turbo_stream, page: @pagy.next, search: params[:search])
    = turbo_frame_tag :pagination, loading: :lazy, src:
  - else
    = turbo_frame_tag :pagination

app/views/posts/by_author.html.slim
- title t(".page_title")
- set_meta_tags og: { title: meta_title(t(".page_title")), description: "Lists of author post" }
- set_meta_tags twitter: { title: meta_title(t(".page_title")), description: "Lists of author post" }

.d-flex.justify-content-between
  h2 = t(".heading")
  div
    = link_to new_post_path, class: "btn btn-primary btn-sm" do
      i.bi.bi-plus-lg.me-1
      = t(".new_post")

== render "filter", path: users_posts_path

= turbo_frame_tag :posts, "data-turbo-action": "advance",
  class: "row row-cols-1 row-cols-md-3 g-4 mb-3" do
  - if @posts.any?
    = render posts
  - else
    .text-center.w-100
      h4.mt-3
        = t(".no_posts")

  = render "turbo_stream_replace_pagination",
    src: users_posts_path(format: :turbo_stream, page: @pagy.next, search: params[:search])

= turbo_frame_tag :pagination

app/views/posts/by_author.turbo_stream.erb
<%= turbo_stream.append :posts do %>
  <%= render posts %>
<% end %>

<%= render "turbo_stream_replace_pagination" %>

app/views/posts/edit.html.slim
- title t(".page_title", title: @post.title)
- set_meta_tags og: { title: meta_title(t(".page_title", title: @post.title)), description: truncate(strip_tags(@post.content),
                length: 150) }
- set_meta_tags twitter: { title: meta_title(t(".page_title", title: @post.title)), description: truncate(strip_tags(@post.content),
                length: 150) }

.row.mb-3
  .col-md-8.offset-md-2
    .card
      .card-body
        h1 = t(".heading")

        == render "form", post: @post

        br

        div
          => link_to t(".actions.show"), @post
          '|
          =< link_to t(".actions.back"), posts_path

app/views/posts/index.html.slim
- if current_page?(posts_path)
  - title t(".page_title")
  - set_meta_tags og: { title: meta_title(t(".page_title")), description: "Lists of post" }
  - set_meta_tags twitter: { title: meta_title(t(".page_title")), description: "Lists of post" }

.d-flex.justify-content-between
  h2 = t(".heading")
  div
    - if user_signed_in?
      = link_to new_post_path, class: "btn btn-primary btn-sm" do
        i.bi.bi-plus-lg.me-1
        = t(".new_post")

== render "filter"

= turbo_frame_tag :posts, "data-turbo-action": "advance",
  class: "row row-cols-1 row-cols-md-3 g-4 mb-3" do
  - if @posts.any?
    = render posts
  - else
    .text-center.w-100
      h4.mt-3
        = t(".no_posts")

  = render "turbo_stream_replace_pagination"

= turbo_frame_tag :pagination

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append :posts do %>
  <%= render posts %>
<% end %>

<%= render "turbo_stream_replace_pagination" %>

app/views/posts/new.html.slim
- title t(".page_title")
- set_meta_tags og: { title: meta_title(t(".page_title")), description: "New post" }
- set_meta_tags twitter: { title: meta_title(t(".page_title")), description: "New post" }

.row.mb-3
  .col-md-8.offset-md-2
    .card
      .card-body
        h2 = t(".heading")

        == render "form", post: @post

        br
        div
          = link_to t(".actions.back"), posts_path

app/views/posts/show.html.slim
- title post.title
- set_meta_tags og: { title: meta_title(post.title), description: truncate(strip_tags(post.content),
                length: 150) }
- set_meta_tags twitter: { title: meta_title(post.title), description: truncate(strip_tags(post.content),
                length: 150) }

/ = turbo_stream_from @post

div id="#{dom_id @post}"
  h2 = @post.title
  / = time_tag @post.updated_at, "data-local": "time-ago"
  .d-flex.flex-row.align-items-center.mb-3
    .fst-italic.me-2 = post.author
    span.dot
    span.text-muted.ms-2
      - if @post.created_at == @post.updated_at
        = "#{t(".posted")}&nbsp;".html_safe
        = post.created_time_ago
      - else
        = "#{t(".edited")}&nbsp;".html_safe
        = post.updated_time_ago
  .mb-3 = @post.content

  .mb-3
    - if user_signed_in?
      = link_to new_post_path, class: "btn btn-primary btn-sm me-1" do
        i.bi.bi-plus-lg.me-1
        = t(".actions.new")
    - if post_author?(@post.user_id)
      = link_to edit_post_path(@post), class: "btn btn-success btn-sm me-1" do
        i.bi.bi-pencil.me-1
        = t(".actions.edit")
      = link_to post_path(@post),
                data: { turbo_confirm: "Are you sure?", turbo_method: :delete },
                class: "btn btn-danger btn-sm" do
        i.bi.bi-trash.me-1
        = t(".actions.delete")

  =< link_to t(".actions.back"), posts_path

  h2.mt-3 = pluralize(format_number_to_human(@post_feedbacks_count), "feedback")
  == render "partials/errors", errors: @feedback&.errors&.full_messages || []
  div[data-turbo-permanent]
    == render "feedbacks/form"
  - if @post_feedbacks_count.positive?
    .d-flex.row.mb-3
      .d-flex.flex-column.col-md-8
        #post-feedbacks.bg-white.px-4.pt-2.pb-4.rounded-3
          = render feedbacks
        - if @pagy.next.present?
          = turbo_frame_tag :pagination, loading: :lazy,
            src: post_feedbacks_path(@post, format: :turbo_stream, page: @pagy.next)